// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`

#ifndef __ICONS_H__
#define __ICONS_H__

#include <cstddef>

#include "icons_35x35.h"
#include "icons_40x40.h"
#include "icons_200x200.h"

typedef enum icon_name {
  air_filter,
  air_pollution,
  co2_svgrepo_com,
  ear_hearing,
  house_thermometer,
  location,
  pressure,
  robo_hw_logo_black,
  wi_humidity_cropped,
  wi_thermometer_cropped,
  wifi,
  wifi_x,
} icon_name_t;

constexpr const unsigned char* getBitmap(icon_name_t icon, size_t size)
{
  switch (icon) {
  case air_filter:
    switch (size) {
    case 35: return air_filter_35x35;
    case 40: return air_filter_40x40;
    case 200: return air_filter_200x200;
    default:
      return nullptr;
    }
  case air_pollution:
    switch (size) {
    case 35: return air_pollution_35x35;
    case 40: return air_pollution_40x40;
    case 200: return air_pollution_200x200;
    default:
      return nullptr;
    }
  case co2_svgrepo_com:
    switch (size) {
    case 35: return co2_svgrepo_com_35x35;
    case 40: return co2_svgrepo_com_40x40;
    case 200: return co2_svgrepo_com_200x200;
    default:
      return nullptr;
    }
  case ear_hearing:
    switch (size) {
    case 35: return ear_hearing_35x35;
    case 40: return ear_hearing_40x40;
    case 200: return ear_hearing_200x200;
    default:
      return nullptr;
    }
  case house_thermometer:
    switch (size) {
    case 35: return house_thermometer_35x35;
    case 40: return house_thermometer_40x40;
    case 200: return house_thermometer_200x200;
    default:
      return nullptr;
    }
  case location:
    switch (size) {
    case 35: return location_35x35;
    case 40: return location_40x40;
    case 200: return location_200x200;
    default:
      return nullptr;
    }
  case pressure:
    switch (size) {
    case 35: return pressure_35x35;
    case 40: return pressure_40x40;
    case 200: return pressure_200x200;
    default:
      return nullptr;
    }
  case robo_hw_logo_black:
    switch (size) {
    case 35: return robo_hw_logo_black_35x35;
    case 40: return robo_hw_logo_black_40x40;
    case 200: return robo_hw_logo_black_200x200;
    default:
      return nullptr;
    }
  case wi_humidity_cropped:
    switch (size) {
    case 35: return wi_humidity_cropped_35x35;
    case 40: return wi_humidity_cropped_40x40;
    case 200: return wi_humidity_cropped_200x200;
    default:
      return nullptr;
    }
  case wi_thermometer_cropped:
    switch (size) {
    case 35: return wi_thermometer_cropped_35x35;
    case 40: return wi_thermometer_cropped_40x40;
    case 200: return wi_thermometer_cropped_200x200;
    default:
      return nullptr;
    }
  case wifi:
    switch (size) {
    case 35: return wifi_35x35;
    case 40: return wifi_40x40;
    case 200: return wifi_200x200;
    default:
      return nullptr;
    }
  case wifi_x:
    switch (size) {
    case 35: return wifi_x_35x35;
    case 40: return wifi_x_40x40;
    case 200: return wifi_x_200x200;
    default:
      return nullptr;
    }
  default:
    return nullptr;
  }
}

#endif