#ifndef __SENSORS_NAMES_H__
#define __SENSORS_NAMES_H__

#include "../defines.h"

#define SDS_SENSOR_NAME "SDS"
#define BME_SENSOR_NAME "BME280"
#define BMP_SENSOR_NAME "BMP280"
#define I2S_NOISE_SENSOR_NAME "ICS43434"
#define RADSENS_SENSOR_NAME "RadSens"
#define GPS_SENSOR_NAME "GPS"
#define SCD4X_SENSOR_NAME "SCD4x"
#define HTTP_ALTRUIST_SENSOR_NAME ATRUIST_URBAN_SENSOR
#define BME680_SENSOR_NAME "BME680"
#define ZMOD4510_SENSOR_NAME "ZMOD4510"


#endif // __SENSORS_NAMES_H__