/**
  ******************************************************************************
  * @file    font16RU.cpp
  * @brief   Russian/Cyrillic 1‑bit bitmap font, compatible with existing
  *          Font16 usage in GUI_Paint (same height, similar width).
  *
  *  IMPORTANT:
  *  - Generate the bitmap data with your converter using:
  *      height = 16 px
  *      width  = 10 px (as in your current config)  or 11 px if you prefer
  *  - Export one continuous 1‑bit array in the exact glyph order you defined:
  *      "!", "\"", "#", ..., "~" plus all Cyrillic letters.
  *  - Paste the generated bytes into Font16_RU_Table below.
  *
  *  The drawing code should treat this as an indexed glyph table:
  *  Char_Offset = glyph_index * Height * bytes_per_row;
  *  where glyph_index is resolved from UTF‑8 by a helper function.
  ******************************************************************************
  */

#ifdef ALTRUIST_INSIGHT

#include "fonts.h"

// Replace the placeholder contents of this array with the bytes
// produced by your bitmap font converter for the exact glyph set
// and order you listed.
//
// Example shape only:
//   const uint8_t Font16_RU_Table[] = {
//       0x00, 0x00, /* ... etc ... */
//   };

const uint8_t Font16_RU_Table[] = {
    // TODO: paste generated 1‑bit bitmap font data here
};

// NOTE:
//  - Set Width to the cell width you used in the converter (10 or 11).
//  - Height must match the pixel height used for each glyph (16).

sFONT Font16_RU = {
    Font16_RU_Table,
    10, /* Width: set to 10 or 11 to match your converter */
    16, /* Height */
};

#endif

