/*
 * Compile nanopb-generated C into this C++ translation unit.
 * Sources: apis/helpers/proto/generated/ from repo proto/ (nanopb 0.4.9.1).
 * Regenerated by scripts/generate_nanopb.py; do not edit the .pb.c files.
 */
#if defined(ALTRUIST_PROTO_PROTOCOL)

#include "sensor/v1/measurement.pb.c"
#include "sensor/v1/sensor.pb.c"
#include "crypto/v1/encrypted.pb.c"
#include "crypto/v1/envelope.pb.c"
#include "device/v1/urban.pb.c"
#include "device/v1/insight.pb.c"
#include "core/v1/message.pb.c"

#endif
